"""empty message

Revision ID: 579b38e811a0
Revises: 44b1d610ab0e
Create Date: 2019-05-02 18:45:17.684207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579b38e811a0'
down_revision = '44b1d610ab0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drive_path', sa.Column('origin', sa.Text(), nullable=True))
    op.drop_column('drive_path', 'orign')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drive_path', sa.Column('orign', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('drive_path', 'origin')
    # ### end Alembic commands ###
