"""empty message

Revision ID: 656376a790ca
Revises: 579b38e811a0
Create Date: 2019-05-02 21:08:48.483575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656376a790ca'
down_revision = '579b38e811a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drive_path', sa.Column('subType', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drive_path', 'subType')
    # ### end Alembic commands ###
